[package]
name = "cumulus"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
directories = "4.0.1"
ctrlc = "3.2.3"
colored = "2"
