name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lua

    steps:
    - uses: actions/checkout@v3
    - name: Clone Lua
      uses: actions/checkout@v3
      with: lua/lua
    - name: List directory
      run: echo test