name: Lua test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lua

    steps:
    - uses: actions/checkout@v3
    - name: Clone Lua
      uses: actions/checkout@v3
      with:
        repository: 'lua/lua'
        ref: 'v5.4.3'
        clean: false
    - name: List directory
      run: echo test